theme: jekyll-theme-minimal
title: Sumeet Pachauri
IIIT-Bhopal
description: 
B-5, Mahavir Campus,
Rajpur Extension, Near Chattarpur
New Delhi-110068

LinkedIn: Profile Hyperlink

kspa4275@gmail.com

+91 9354211844

logo: "profile pic.png"
