theme: jekyll-theme-minimal
title: Sumeet Pachauri UG-IT, IIIT Bhopal
description:  Email - kspa4275@gmail.com     Mobile - +91-9354211844     New Delhi  
logo: "profile pic.png"
<div class="badge-base LI-profile-badge" data-locale="en_US" data-size="medium" data-theme="light" data-type="VERTICAL" data-vanity="sumeet-iiitb" data-version="v1"><a class="badge-base__link LI-simple-link" href="https://in.linkedin.com/in/sumeet-iiitb?trk=profile-badge">Sumeet P.</a></div>
              
